spring:
  kafka:
    bootstrap-servers: ${SERVER_URI}   # Kafka broker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${GROUP_ID_KAFKA}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: net.engineeringdigest.journalApp.model

    properties:
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${USERNAME_KAFKA}' password='${PASSWORD_KAFKA}';
      security.protocol: SASL_SSL
      session.timeout.ms: 30000
      client.id: ${CLIENT_ID}


  redis:
    host: ${REDIS_HOST}
    port: 17503
    password: ${REDIS_PASSWORD}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${APP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080
  servlet:
    context-path: /journal-dev
    #local Redis - wsl
    #    host: localhost
    #   port: 6379