spring:
  profiles:
    active: dev



server:
  port: 8081
  servlet:
    context-path: /journal


weather:
  api:
    Key: ${WEATHER_API_KEY}

#internal/Sare root wale error off
#logging:
#  level:
#    root: OFF

#class wise off error
#logging:
#  level:
#    net:
#      engineeringdigest:
#        journalApp:
#          service:
#            UserService: OFF

